#index:
#    path: /
#    controller: App\Controller\DefaultController::index

ip_store_addpage:
    path:     /ipstore/addtostore
    controller: App\Controller\IpStoreController::addAction

#ip_store:
#    resource: "@IpStoreBundle/Resources/config/routing.yml"
#    prefix:   /